# Generated by Django 3.2.8 on 2021-10-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=50)),
                ('creation_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['creation_time', 'name'],
            },
        ),
    ]
